on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
  push:
    branches:
      - 'main'
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write
 
name: Testing
jobs:
  check_comments:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - uses: MinecraftForge/Actionable@v1
        with:
          gh_app_key: ${{ secrets.GH_APP_KEY }}
          gh_app_name: ${{ secrets.GH_APP_NAME }}
          triage_team: triage
          triage_project: 4
